apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartahub
  labels:
    app: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: cartahub
        image: rodrigokondo/cartahub
        ports:
        - containerPort: 5000