version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $CIRCLE_BUILDk_URL|tee -a index.html
          cat index.htmlK
          docker build -f docker/Dockerfile -t rodrigokondo/cartahub:latest .
          mkdir -p /tmp/image
          docker save -o /tmp/image/image.tar  rodrigokondo/cartahub:latest
      - persist_to_workspace:
          root: /tmp/image
          paths:
            - image.tar
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - setup_remote_docker
      - run: |
          docker load -i /tmp/image.tar
          docker run  rodrigokondo/cartahub:latest carta-devops test
  push-image:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - setup_remote_docker
      - run: |
          docker load -i /tmp/image.tar
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push rodrigokondo/cartahub:latest
workflows:
  version: 2
  build_push_docker:
    jobs:
      - build
      - test:
          requires:
            - build
      - push-image:
          requires:
            - test
          filters:
            branches:
              only: master