version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          cd docker
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t rodrigokondo/cartahub:$TAG .
  push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push rodrigokondo/cartahub:$TAG
workflows:
  build_push_docker:
    jobs:
      - build
      - push_image:
        requires:
          - build