version: 2.1

workflows:
  main:
  jobs:
    build:
      steps:
        - run:
          name: "faz tudo"
          command: |
            apk add docker-cli
            docker build -t rodrigokondo/cartahub:$CIRCLE_BRANCH
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            TAG="1.${CIRCLE_BUILD_NUM}"
            docker push rodrigokondo/cartahub:$TAG
