version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
        docker_layer_caching: true
      - run: |
          cd docker
          docker build -t rodrigokondo/cartahub .
  push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t rodrigokondo/cartahub:$TAG .
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push rodrigokondo/cartahub:$TAG
workflows:
  version: 2
  build_push_docker:
    jobs:
      - build
      - push_image:
          requires:
            - build