version: 2.1
jobs:
  setup:
    steps:
      - run: apk add docker-cli
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  build:
    steps:
      - checkout
      - run: docker build -t rodrigokondo/cartahub:$CIRCLE_BRANCH
  push:
    steps:
      - run: TAG="1.${CIRCLE_BUILD_NUM}"
      - run: docker push rodrigokondo/cartahub:$TAG
workflow:
  version: 2
  pipeline:
    jobs:
      - setup
      - build
      - push

















