version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          cd docker
          docker build -t rodrigokondo/cartahub:$TAG .
          docker save -o image.tar  rodrigokondo/cartahub:$TAG
      - persist_to_workspace:
          root: /home/circleci/project/docker
          paths:
            - image.tar
  push-image:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - setup_remote_docker
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker load -i /tmp/image.tar
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push rodrigokondo/cartahub:$TAG
workflows:
  version: 2
  build_push_docker:
    jobs:
      - build
      - push-image:
          requires:
            - build